
CREATE DATABASE IF NOT EXISTS newsletter_db
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;


USE newsletter_db;


CREATE TABLE IF NOT EXISTS newslettertable (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  date_inscription DATETIME DEFAULT CURRENT_TIMESTAMP
);
